### ISSUE TITLE
`\iow_open:Nn` in ConTeXt MkII produces `\write is already defined` and `Bad number (16)`

### ISSUE THREAD

**Issue by Witiko** [latex3/latex3#1103]
## Minimal working example

Create file `example.tex` with the following content:

``` tex
\input expl3-generic
\ExplSyntaxOn
\iow_new:N   \l_output_stream
\iow_open:Nn \l_output_stream { output.txt }
\iow_now:Nn  \l_output_stream { foo~bar    }
\iow_close:N \l_output_stream
\ExplSyntaxOff
\starttext
\input output.txt
\stoptext
```

Run `texexec example.tex` with up-to-date TeX Live 2022.

## Expected outcome

A file `example.pdf` with the text *foo bar* is produced without error.

## Actual outcome

The following output is printed onto the terminal:

```
...
warning         : \write \l_output_stream is already defined (\relax it first)
! Bad number (16).
<argument> \l_output_stream

l.4 \iow_open:Nn \l_output_stream { output.txt }

? X
No pages of output.
Transcript written on example.log.
```

## Plain TeX code that produces the expected outcome

``` tex
\input expl3-generic
\ExplSyntaxOn
\newwrite            \l_output_stream
\immediate \openout  \l_output_stream { output.txt }
\immediate \write    \l_output_stream { \exp_not:n { foo~bar } }
\immediate \closeout \l_output_stream
\ExplSyntaxOff
\starttext
\input output.txt
\stoptext
```

**Comment by pablgonz** [comment]
@Witiko  If I remember correctly the ConTeXt support is not official from the LaTeX team, anyway, I cannot reproduce your problem using `context example.tex`, as far as I understand `texexexec` (Ruby script) is deprecated (https://tex.stackexchange.com/a/461359) and I can't run it on my system (fedora 36):

```
$ texexec 
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rexml/document (LoadError)
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/texlive/2022/texmf-dist/scripts/context/ruby/base/ctx.rb:20:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/texlive/2022/texmf-dist/scripts/context/ruby/base/tex.rb:29:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/texlive/2022/texmf-dist/scripts/context/ruby/texexec.rb:19:in `<main>'
```

However, this is the output of `context example.tex` :

```
$ context example.tex 

resolvers       | formats | executing runner 'run luatex format': /usr/local/texlive/2022/bin/x86_64-linux/luatex --jobname="example" --fmt=/home/pablo/.texlive2022/texmf-var/luatex-cache/context/a86c089b384a3076dc514ba966a1fac9/formats/luatex/cont-en.fmt --lua=/home/pablo/.texlive2022/texmf-var/luatex-cache/context/a86c089b384a3076dc514ba966a1fac9/formats/luatex/cont-en.lui cont-yes.mkiv --c:currentrun=1 --c:fulljobname="./example.tex" --c:input="./example.tex" --c:kindofrun=1 --c:maxnofruns=9 --c:texmfbinpath="/usr/local/texlive/2022/bin/x86_64-linux"
This is LuaTeX, Version 1.15.0 (TeX Live 2022) 
 system commands enabled.
open source     > level 1, order 1, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-yes.mkiv'
system          > 
system          > ConTeXt  ver: 2021.03.05 19:11 MKIV  fmt: 2022.4.28  int: english/english
system          > 
system          > 'cont-new.mkiv' loaded
open source     > level 2, order 2, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-new.mkiv'
system          > beware: some patches loaded from cont-new.mkiv
close source    > level 2, order 2, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-new.mkiv'
system          > files > jobname 'example', input './example', result 'example'
fonts           > latin modern fonts are not preloaded
languages       > language 'en' is active
open source     > level 2, order 3, name '/home/pablo/example.tex'
open source     > level 3, order 4, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-generic.tex'
open source     > level 4, order 5, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-code.tex'
fonts           > beware: no fonts are loaded yet, using 'lm mono' in box
close source    > level 4, order 5, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-code.tex'
open source     > level 4, order 6, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-luatex.def'
close source    > level 4, order 6, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-luatex.def'
close source    > level 3, order 6, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-generic.tex'
fonts           > preloading latin modern fonts (second stage)
fonts           > 'fallback modern-designsize rm 12pt' is loaded
open source     > level 3, order 7, name 'output.txt'
close source    > level 3, order 7, name 'output.txt'
backend         > xmp > using file '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/lpdf-pdx.xml'
pages           > flushing realpage 1, userpage 1, subpage 1
close source    > level 2, order 7, name '/home/pablo/example.tex'
close source    > level 1, order 7, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-yes.mkiv'

mkiv lua stats  > used config file: selfautoparent:/texmfcnf.lua;selfautoparent:/texmf-dist/web2c/texmfcnf.lua
mkiv lua stats  > used cache path: readable+writable: '/home/pablo/.texlive2022/texmf-var/luatex-cache/context/a86c089b384a3076dc514ba966a1fac9'
mkiv lua stats  > resource resolver: loadtime 0.209 seconds, 1 scans with scantime 0.000 seconds, 0 shared scans, 24 found files, scanned paths: /home/pablo/texmf
mkiv lua stats  > stored bytecode data: 454 modules (0.469 sec), 96 tables (0.016 sec), 550 chunks (0.485 sec)
mkiv lua stats  > traced context: maxstack: 1442, freed: 0, unreachable: 1442
mkiv lua stats  > cleaned up reserved nodes: 57 nodes, 10 lists of 461
mkiv lua stats  > node memory usage: 11 attribute, 4 attribute_list, 1 glue, 55 glue_spec, 3 kern, 2 penalty, 2 temp, 2 user_defined
mkiv lua stats  > node list callback tasks: 8 unique task lists, 7 instances (re)created, 38 calls
mkiv lua stats  > driver time: 0.098 seconds 
mkiv lua stats  > used backend: pdf (backend for directly generating pdf output)
mkiv lua stats  > jobdata time: 0.001 seconds saving, 0.000 seconds loading
mkiv lua stats  > callbacks: internal: 154, file: 73191, direct: 15, late: 0, function 7167, total: 80527 (0 per page)
mkiv lua stats  > result saved in file: example.pdf, compresslevel 3, objectcompresslevel 1
mkiv lua stats  > loaded patterns: en::1, load time: 0.000
mkiv lua stats  > loaded fonts: 3 files: latinmodern-math.otf, lmmono10-regular.otf, lmroman12-regular.otf
mkiv lua stats  > font engine: otf 3.113, afm 1.513, tfm 1.000, 8 instances, 3 shared in backend, 3 common vectors, 0 common hashes, load time 0.236 seconds 
mkiv lua stats  > used platform: linux-64, type: unix, binary subtree: bin
mkiv lua stats  > used engine: luatex version: 1.15, functionality level: 7509, banner: this is luatex, version 1.15.0 (tex live 2022)
mkiv lua stats  > used hash slots: 59425 of 65536 + 200000
mkiv lua stats  > lua properties: engine: lua 5.3, used memory: 172 MB, ctx: 172 MB, max: unknown MB, hash chars: min(64,40), symbol mask: utf (τεχ)
mkiv lua stats  > runtime: 1.452 seconds, 1 processed pages, 1 shipped pages, 0.689 pages/second

resolvers       | formats | executing runner 'run luatex format': /usr/local/texlive/2022/bin/x86_64-linux/luatex --jobname="example" --fmt=/home/pablo/.texlive2022/texmf-var/luatex-cache/context/a86c089b384a3076dc514ba966a1fac9/formats/luatex/cont-en.fmt --lua=/home/pablo/.texlive2022/texmf-var/luatex-cache/context/a86c089b384a3076dc514ba966a1fac9/formats/luatex/cont-en.lui cont-yes.mkiv --c:currentrun=2 --c:fulljobname="./example.tex" --c:input="./example.tex" --c:kindofrun=2 --c:maxnofruns=9 --c:texmfbinpath="/usr/local/texlive/2022/bin/x86_64-linux"
This is LuaTeX, Version 1.15.0 (TeX Live 2022) 
 system commands enabled.
open source     > level 1, order 1, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-yes.mkiv'
system          > 
system          > ConTeXt  ver: 2021.03.05 19:11 MKIV  fmt: 2022.4.28  int: english/english
system          > 
system          > 'cont-new.mkiv' loaded
open source     > level 2, order 2, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-new.mkiv'
system          > beware: some patches loaded from cont-new.mkiv
close source    > level 2, order 2, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-new.mkiv'
system          > files > jobname 'example', input './example', result 'example'
fonts           > latin modern fonts are not preloaded
languages       > language 'en' is active
open source     > level 2, order 3, name '/home/pablo/example.tex'
open source     > level 3, order 4, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-generic.tex'
open source     > level 4, order 5, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-code.tex'
fonts           > beware: no fonts are loaded yet, using 'lm mono' in box
close source    > level 4, order 5, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-code.tex'
open source     > level 4, order 6, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-luatex.def'
close source    > level 4, order 6, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-luatex.def'
close source    > level 3, order 6, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-generic.tex'
fonts           > preloading latin modern fonts (second stage)
fonts           > 'fallback modern-designsize rm 12pt' is loaded
open source     > level 3, order 7, name 'output.txt'
close source    > level 3, order 7, name 'output.txt'
backend         > xmp > using file '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/lpdf-pdx.xml'
pages           > flushing realpage 1, userpage 1, subpage 1
close source    > level 2, order 7, name '/home/pablo/example.tex'
close source    > level 1, order 7, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-yes.mkiv'

mkiv lua stats  > used config file: selfautoparent:/texmfcnf.lua;selfautoparent:/texmf-dist/web2c/texmfcnf.lua
mkiv lua stats  > used cache path: readable+writable: '/home/pablo/.texlive2022/texmf-var/luatex-cache/context/a86c089b384a3076dc514ba966a1fac9'
mkiv lua stats  > resource resolver: loadtime 0.191 seconds, 1 scans with scantime 0.000 seconds, 0 shared scans, 24 found files, scanned paths: /home/pablo/texmf
mkiv lua stats  > stored bytecode data: 454 modules (0.445 sec), 96 tables (0.015 sec), 550 chunks (0.460 sec)
mkiv lua stats  > traced context: maxstack: 1442, freed: 0, unreachable: 1442
mkiv lua stats  > cleaned up reserved nodes: 57 nodes, 10 lists of 461
mkiv lua stats  > node memory usage: 11 attribute, 4 attribute_list, 1 glue, 55 glue_spec, 3 kern, 2 penalty, 2 temp, 2 user_defined
mkiv lua stats  > node list callback tasks: 8 unique task lists, 7 instances (re)created, 38 calls
mkiv lua stats  > driver time: 0.088 seconds 
mkiv lua stats  > used backend: pdf (backend for directly generating pdf output)
mkiv lua stats  > jobdata time: 0.001 seconds saving, 0.000 seconds loading
mkiv lua stats  > callbacks: internal: 154, file: 73191, direct: 15, late: 0, function 7167, total: 80527 (80527 per page)
mkiv lua stats  > randomizer: initialized with value 0.92246527969837
mkiv lua stats  > result saved in file: example.pdf, compresslevel 3, objectcompresslevel 1
mkiv lua stats  > loaded patterns: en::1, load time: 0.000
mkiv lua stats  > loaded fonts: 3 files: latinmodern-math.otf, lmmono10-regular.otf, lmroman12-regular.otf
mkiv lua stats  > font engine: otf 3.113, afm 1.513, tfm 1.000, 8 instances, 3 shared in backend, 3 common vectors, 0 common hashes, load time 0.198 seconds 
mkiv lua stats  > used platform: linux-64, type: unix, binary subtree: bin
mkiv lua stats  > used engine: luatex version: 1.15, functionality level: 7509, banner: this is luatex, version 1.15.0 (tex live 2022)
mkiv lua stats  > used hash slots: 59424 of 65536 + 200000
mkiv lua stats  > lua properties: engine: lua 5.3, used memory: 167 MB, ctx: 167 MB, max: unknown MB, hash chars: min(64,40), symbol mask: utf (τεχ)
mkiv lua stats  > runtime: 1.362 seconds, 1 processed pages, 1 shipped pages, 0.734 pages/second

resolvers       | formats | executing runner 'run luatex format': /usr/local/texlive/2022/bin/x86_64-linux/luatex --jobname="example" --fmt=/home/pablo/.texlive2022/texmf-var/luatex-cache/context/a86c089b384a3076dc514ba966a1fac9/formats/luatex/cont-en.fmt --lua=/home/pablo/.texlive2022/texmf-var/luatex-cache/context/a86c089b384a3076dc514ba966a1fac9/formats/luatex/cont-en.lui cont-yes.mkiv --c:currentrun=3 --c:fulljobname="./example.tex" --c:input="./example.tex" --c:kindofrun=2 --c:maxnofruns=9 --c:texmfbinpath="/usr/local/texlive/2022/bin/x86_64-linux"
This is LuaTeX, Version 1.15.0 (TeX Live 2022) 
 system commands enabled.
open source     > level 1, order 1, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-yes.mkiv'
system          > 
system          > ConTeXt  ver: 2021.03.05 19:11 MKIV  fmt: 2022.4.28  int: english/english
system          > 
system          > 'cont-new.mkiv' loaded
open source     > level 2, order 2, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-new.mkiv'
system          > beware: some patches loaded from cont-new.mkiv
close source    > level 2, order 2, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-new.mkiv'
system          > files > jobname 'example', input './example', result 'example'
fonts           > latin modern fonts are not preloaded
languages       > language 'en' is active
open source     > level 2, order 3, name '/home/pablo/example.tex'
open source     > level 3, order 4, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-generic.tex'
open source     > level 4, order 5, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-code.tex'
fonts           > beware: no fonts are loaded yet, using 'lm mono' in box
close source    > level 4, order 5, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-code.tex'
open source     > level 4, order 6, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-luatex.def'
close source    > level 4, order 6, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-luatex.def'
close source    > level 3, order 6, name '/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-generic.tex'
fonts           > preloading latin modern fonts (second stage)
fonts           > 'fallback modern-designsize rm 12pt' is loaded
open source     > level 3, order 7, name 'output.txt'
close source    > level 3, order 7, name 'output.txt'
backend         > xmp > using file '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/lpdf-pdx.xml'
pages           > flushing realpage 1, userpage 1, subpage 1
close source    > level 2, order 7, name '/home/pablo/example.tex'
close source    > level 1, order 7, name '/usr/local/texlive/2022/texmf-dist/tex/context/base/mkiv/cont-yes.mkiv'

mkiv lua stats  > used config file: selfautoparent:/texmfcnf.lua;selfautoparent:/texmf-dist/web2c/texmfcnf.lua
mkiv lua stats  > used cache path: readable+writable: '/home/pablo/.texlive2022/texmf-var/luatex-cache/context/a86c089b384a3076dc514ba966a1fac9'
mkiv lua stats  > resource resolver: loadtime 0.143 seconds, 1 scans with scantime 0.000 seconds, 0 shared scans, 24 found files, scanned paths: /home/pablo/texmf
mkiv lua stats  > stored bytecode data: 454 modules (0.375 sec), 96 tables (0.014 sec), 550 chunks (0.389 sec)
mkiv lua stats  > traced context: maxstack: 1442, freed: 0, unreachable: 1442
mkiv lua stats  > cleaned up reserved nodes: 57 nodes, 10 lists of 461
mkiv lua stats  > node memory usage: 11 attribute, 4 attribute_list, 1 glue, 55 glue_spec, 3 kern, 2 penalty, 2 temp, 2 user_defined
mkiv lua stats  > node list callback tasks: 8 unique task lists, 7 instances (re)created, 38 calls
mkiv lua stats  > driver time: 0.087 seconds 
mkiv lua stats  > used backend: pdf (backend for directly generating pdf output)
mkiv lua stats  > jobdata time: 0.001 seconds saving, 0.000 seconds loading
mkiv lua stats  > callbacks: internal: 154, file: 73191, direct: 15, late: 0, function 7167, total: 80527 (80527 per page)
mkiv lua stats  > randomizer: resumed with value 0.92246527969837
mkiv lua stats  > result saved in file: example.pdf, compresslevel 3, objectcompresslevel 1
mkiv lua stats  > loaded patterns: en::1, load time: 0.000
mkiv lua stats  > loaded fonts: 3 files: latinmodern-math.otf, lmmono10-regular.otf, lmroman12-regular.otf
mkiv lua stats  > font engine: otf 3.113, afm 1.513, tfm 1.000, 8 instances, 3 shared in backend, 3 common vectors, 0 common hashes, load time 0.205 seconds 
mkiv lua stats  > used platform: linux-64, type: unix, binary subtree: bin
mkiv lua stats  > used engine: luatex version: 1.15, functionality level: 7509, banner: this is luatex, version 1.15.0 (tex live 2022)
mkiv lua stats  > used hash slots: 59424 of 65536 + 200000
mkiv lua stats  > lua properties: engine: lua 5.3, used memory: 167 MB, ctx: 167 MB, max: unknown MB, hash chars: min(64,40), symbol mask: utf (τεχ)
mkiv lua stats  > runtime: 1.289 seconds, 1 processed pages, 1 shipped pages, 0.776 pages/second
system          | total runtime: 5.233 seconds
```

**Comment by Witiko** [comment]
@pablgonz 

> However, this is the output of `context example.tex`:

Running `context example.tex` uses the ConTeXt MkIV format. My report is for when you run `texexec example.tex`, which uses the ConTeXt MkII format. Context MkII and ConTeXt MkIV are fundamentally different formats.

**Comment by pablgonz** [comment]
@Witiko Sorry for my bad English (not my forte), here is the output using `texexec example.tex`:

```
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=cont-en 2022.6.12)  25 JUN 2022 21:01
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**example.tex
(./example.tex

ConTeXt  ver: 2021.03.05 19:11 MKII  fmt: 2022.6.12  int: english/english

system          : cont-new.mkii loaded
(/usr/local/texlive/2022/texmf-dist/tex/context/base/mkii/cont-new.mkii
systems         : beware: some patches loaded from cont-new.mkii
)
system          : cont-sys.tex loaded
(/usr/local/texlive/2022/texmf-config/tex/context/user/cont-sys.tex
(/usr/local/texlive/2022/texmf-dist/tex/context/base/mkii/type-siz.mkii)
(/usr/local/texlive/2022/texmf-dist/tex/context/base/mkii/type-one.mkii))
system          : example.top loaded
(./example.top)
bodyfont        : 12pt rm is loaded
language        : patterns nl->texnansi:texnansi->1->2:2 nl->ec:ec->2->2:2 us->
ec:ec->3->2:3 de->texnansi:texnansi->4->3:3 de->ec:ec->5->3:3 da->ec:ec->6->2:2
 sv->ec:ec->7->2:2 af->ec:ec->8->2:2 gb->ec:ec->9->2:2 fr->texnansi:texnansi->1
0->2:2 fr->ec:ec->11->2:2 es->ec:ec->12->2:2 ca->ec:ec->13->2:2 it->texnansi:te
xnansi->14->2:2 it->ec:ec->15->2:2 la->ec:ec->16->2:2 pt->texnansi:texnansi->17
->2:2 pt->ec:ec->18->2:2 ro->ec:ec->19->2:2 pl->pl0:pl0->20->2:2 pl->ec:ec->21-
>2:2 pl->qx:qx->22->2:2 cs->il2:il2->23->2:2 cs->ec:ec->24->2:2 sk->il2:il2->25
->2:2 sk->ec:ec->26->2:2 hr->ec:ec->27->2:2 sl->ec:ec->28->2:2 tr->ec:ec->29->2
:2 tk->ec:ec->30->1:2 lt->l7x:l7x->31->2:2 agr->agr:agr->33->2:2 fi->ec:ec->34-
>2:2 hu->ec:ec->35->2:2 ru->t2a:t2a->37->2:2 uk->t2a:t2a->38->3:3  loaded
specials        : dvips loaded
\openout3 = `example.tui'.

\openout0 = `example-mpgraph.mp'.

systems         : system commands are enabled
language        : language en is active
specials        : loading definition file tpd
(/usr/local/texlive/2022/texmf-dist/tex/context/base/mkii/spec-tpd.mkii
specials        : loading definition file fdf
(/usr/local/texlive/2022/texmf-dist/tex/context/base/mkii/spec-fdf.mkii))
(/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-generic.tex
Package: expl3 2022-06-16 L3 programming layer (loader)

(/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-code.tex
Package: expl3 2022-06-16 L3 programming layer (code)
)
(/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def
File: l3backend-pdftex.def 2022-04-20 v L3 backend support: PDF output (pdfTeX)

))
\openout7 = `output.txt'.


(./example.tuo) (./example.tuo) (./example.tuo) (./example.tuo) (./example.tuo)
(./example.tuo) (./example.tuo) (./example.tuo) (./example.tuo) (./example.tuo)
(./example.tuo)
publications    : file example.bbl not found, waiting for bibtex
(./example.tuo)
systems         : begin file example at line 8
(./output.txt)
fonts           : resetting map file list
{/usr/local/texlive/2022/texmf-dist/fonts/map/pdftex/context/original-empty.map
}
fonts           : using map file: original-base
{/usr/local/texlive/2022/texmf-dist/fonts/map/pdftex/context/original-base.map}
fonts           : using map file: original-ams-base
{/usr/local/texlive/2022/texmf-dist/fonts/map/pdftex/context/original-ams-base.
map}
fonts           : using map file: original-public-lm
{/usr/local/texlive/2022/texmf-dist/fonts/map/pdftex/context/original-public-lm
.map}
fonts           : using map file: lm-ec
{/usr/local/texlive/2022/texmf-dist/fonts/map/dvips/lm/lm-ec.map}
fonts           : using map file: lm-math
{/usr/local/texlive/2022/texmf-dist/fonts/map/dvips/lm/lm-math.map}
fonts           : using map file: lm-rm
{/usr/local/texlive/2022/texmf-dist/fonts/map/dvips/lm/lm-rm.map}
fonts           : using map file: original-ams-euler
{/usr/local/texlive/2022/texmf-dist/fonts/map/pdftex/context/original-ams-euler
.map} (/usr/local/texlive/2022/texmf-dist/tex/context/base/mkii/sort-def.mkii)
(/usr/local/texlive/2022/texmf-dist/tex/context/base/mkii/sort-lan.mkii)
[1.1]
systems         : end file example at line 10
 ) 
Here is how much of TeX's memory you used:
 12261 strings out of 455439
 243075 string characters out of 5509319
 4903673 words of memory out of 9304019
 53584 multiletter control sequences out of 15000+600000
 548037 words of font info for 51 fonts, out of 8000000 for 9000
 581 hyphenation exceptions out of 8191
 46i,17n,57p,222b,920s stack positions out of 10000i,1000n,20000p,200000b,200000s
{/usr/local/texlive/2022/texmf-dist/fonts/enc/dvips/lm/lm-ec.enc}</usr/local/
texlive/2022/texmf-dist/fonts/type1/public/lm/lmr12.pfb>

pdfTeX warning: pdftex: no GlyphToUnicode entry has been inserted yet!
Output written on example.pdf (1 page, 20499 bytes).
PDF statistics:
 13 PDF objects out of 1000 (max. 8388607)
 9 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)
```

![imagen](https://user-images.githubusercontent.com/2289461/175795179-0701035f-d7df-499f-bceb-9b373aedbbd7.png)

**Comment by pablgonz** [comment]
@Witiko APs...I forgot to write that I had to run `gem install rexml` for it to work, otherwise I would get the same output as you, anyway I think it is *not expl3`s fault* :D

**Comment by Witiko** [comment]
> @Witiko APs...I forgot to write that I had to run `gem install rexml` for it to work, otherwise I would get the same output as you, anyway I think it is _not expl3`s fault_ :D

Thank you, I would never have guessed this. Much appreciated. 👍

**Comment by Witiko** [comment]
@pablgonz Sadly cannot confirm that running `gem install rexml` fixes this: https://github.com/Witiko/lt3luabridge/runs/7057700103

**Comment by pablgonz** [comment]
@Witiko This has worked on my local machine, I use Fedora so I don't know how it will be on other distributions...you can place the output of `texexexec --help` ...that's where I noticed the problem

**Comment by Witiko** [comment]
@pablgonz You are right, my issue from https://github.com/latex3/latex3/issues/1103#issuecomment-1166396267 was due to using TeX Live 2021 Docker image. Thanks again.
